#!/usr/bin/env bash
set -euo pipefail

# Launch ComfyUI (Apple Silicon / MPS) wired to the shared model store.
# Web UI at http://localhost:8188

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/env.sh"
COMFY_DIR="$SCRIPT_DIR/comfyui"

# Point ComfyUI at the common model store (~/ai-models/comfyui) instead of its
# own comfyui/models dir. Regenerated automatically after a fresh clone.
CONFIG="$COMFY_DIR/extra_model_paths.yaml"
cat > "$CONFIG" <<YAML
# Auto-generated by comfyui-start.sh — points ComfyUI at the shared model store.
shared_store:
    base_path: $COMFY_MODELS_DIR
    checkpoints: checkpoints
    diffusion_models: diffusion_models
    unet: unet
    text_encoders: text_encoders
    clip: clip
    clip_vision: clip_vision
    vae: vae
    loras: loras
    controlnet: controlnet
    upscale_models: upscale_models
    embeddings: embeddings
    style_models: style_models
YAML

source "$COMFY_DIR/.venv/bin/activate"
cd "$COMFY_DIR"

echo "ComfyUI models  <- $COMFY_MODELS_DIR"
echo "HuggingFace cache <- $HF_HOME"
echo

exec python main.py --force-fp16 --preview-method auto "$@"
